projects:
  root_directories:
    - "/Users/mike/dev/readrise-app"
    - "/Users/mike/dev/bookms"
    - "/Users/mike/dev/spendings"
    - "/Users/mike/dev/Test"
    - "/Users/mike/dev/platgame"
    - "/Users/mike/dev/jira-fetcher"
    - "/Users/mike/dev/locapp"
    - "/Users/mike/dev/visausa"
    - "/Users/mike/dev/angular-tour-of-heroes"
    - "/Users/mike/dev/magicbot"
    - "/Users/mike/dev/export"
    - "/Users/mike/dev/trading"
    - "/Users/mike/dev/musicsearch"
    - "/Users/mike/dev/coinmk-mcp"

time_analysis:
  start_date: "2024-01-01"
  end_date: "2025-09-18"

filters:
  exclude_directories:
    - "node_modules"
    - "target"
    - "build"
    - "dist"
    - ".git"
    - "__pycache__"
    - ".venv"
    - "venv"
    - ".pytest_cache"
    - "coverage"
    - "vendor"
    - "bower_components"

  exclude_files:
    - "*.min.js"
    - "*.min.css"
    - "*.log"
    - "*.tmp"
    - "*.pyc"
    - "*.class"
    - "*.jar"
    - "*.war"
    - "*.exe"
    - "*.dll"
    - "*.so"
    - "*.dylib"
    - "*.a"
    - "*.lib"
    - "package-lock.json"
    - "yarn.lock"
    - "Pipfile.lock"

output:
  format: ["json", "csv", "html"]

# Git analysis settings
git:
  # Historical checkout - analyzes LOC at end_date state for accuracy
  checkout_target_date: true  # Checkout commit matching end date before LOC analysis
  preserve_working_directory: true  # Stash uncommitted changes before checkout

  # Exclude automated commits from analysis
  exclude_authors:
    - "Jenkins"
    - "jenkins"
    - "Jenkins Automation"
    - "GitHub Actions"
    - "github-actions[bot]"
    - "dependabot[bot]"
    - "renovate[bot]"
    - "bot"
    - "automation"
    - "CI/CD"
    - "deploy"

# Commits reporting settings
reporting:
  commits_reports:
    generate_html: true
    generate_csv: true
    max_commit_message_length: 100
    max_files_per_commit_display: 5

  # Error reporting settings
  error_reports:
    generate_html: true
    generate_csv: true
    include_tracebacks: true