projects:
  root_directories:
    - "/path/to/your/projects"
    - "."  # Current directory

time_analysis:
  start_date: "2024-01-01"
  end_date: "2025-09-18"

filters:
  exclude_directories:
    - "node_modules"
    - "target"
    - "build"
    - "dist"
    - ".git"
    - "__pycache__"
    - ".venv"
    - "venv"
    - ".pytest_cache"
    - "coverage"

  exclude_files:
    - "*.min.js"
    - "*.min.css"
    - "*.log"
    - "*.tmp"
    - "*.pyc"
    - "*.class"
    - "*.jar"
    - "*.war"
    - "package-lock.json"
    - "yarn.lock"

output:
  format: ["json", "csv", "html"]

# Git analysis settings
git:
  # Historical checkout - analyzes LOC at end_date state for accuracy
  checkout_target_date: true
  preserve_working_directory: true

  # Exclude automated commits from analysis
  exclude_authors:
    - "GitHub Actions"
    - "github-actions[bot]"
    - "dependabot[bot]"
    - "Jenkins"
    - "bot"

# Commits reporting settings
reporting:
  commits_reports:
    generate_html: true
    generate_csv: true
    max_commit_message_length: 100
    max_files_per_commit_display: 5